#!/bin/bash

export DUMPS_DIRECTORY='/home/roman/Backups/Arch'
export DATES_FILE='dumpdates'

re='^[0-9]+$'
if ! [[ $1 =~ $re ]] ; then
   echo "error: 1st argument must be a dump level" >&2
   exit 1
fi

export TODAYS_SECONDS=echo $(($(($((10#$(date +%H) * 60 + 10#$(date +%M))) * 60)) + 10#$(date +%S)))

export command=$(\
    printf "dump -%su -z9 -D %s/%s -f %s/ArchGreenDump-%slvl-gz-%s.%s.dump /"\
    $1 $DUMPS_DIRECTORY $DATES_FILE $DUMPS_DIRECTORY $1 $(date +%d.%m.%y) $TODAYS_SECONDS\
)

cp $DUMPS_DIRECTORY/$DATES_FILE $DUMPS_DIRECTORY/$DATES_FILE.old &> /dev/null
echo 'executing command:' > /dev/tty
echo $command > /dev/tty

echo "Do you want to continue? [Y/n] " > /dev/tty
export answer
read answer
echo '' > /dev/tty
positive_answers=("Y" "y" "")
answer_yes_found=0
for i in "${positive_answers[@]}"; do
    if [[ $answer == $i ]]; then
        echo "continuing..."  # todo remove
        eval $command
        answer_yes_found=1
        break
    fi
done

if [ $answer_yes_found == 0 ]; then
    echo "cancelled"
fi
